namespace Engine
{
    /// <summary>
    /// Enum <c>Resource</c> represents the types of resources held at the
    /// faction level.
    /// </summary>
    public enum Resource
    {
        /// <summary>
        /// minerals generated by mining districts.
        /// </summary>
        Minerals,
        /// <summary>
        /// metals produced by foundries.
        /// </summary>
        Metals
    }
}
